name : Mark Lacsamana
brand : Mark Lacsamana
description : This is the description of my project
keyword : 
url : emkey.github.io
email : mllacsamana@gmail.com
twitter : emkey
github : emkey
author : emkey
year : 2016
markdown : kramdown
exclude :
  - node_modules
