name : Mark Lacsamana
brand : Mark Lacsamana
description : Portfolio of Mark Lacsamana UX Designer, Researcher and Calligrapher
keyword : Designer, User Experience, User Interface, Technology, Research, Calligraphy, Design
url : https://emkey.github.io
email : mllacsamana@gmail.com
twitter : emkey
github : emkey
author : Mark Lester C. Lacsamana
year : 2017
markdown : kramdown
exclude :
  - node_modules
